FROM roboticsplus/image-cpp:1.7.0-22.04

ARG USER=rpl
ARG UID=1000
ARG GID=1000

USER root
WORKDIR /root

# Switch to bash
RUN chsh -s /bin/bash "${USER}"

RUN apt-get update &&    \
    apt-get install -fy  \
    curl                 \
    zip                  \
    pkg-config           \
    autoconf             \
    automake             \
    libc6=2.35-0ubuntu3.10 \
    valgrind             \
    && apt-get clean     \
    && rm -rf /var/cache/* /var/lib/apt/lists/*

USER ${UID}
WORKDIR /home/${USER}

ENV PATH="${PATH}:/home/${USER}/.local/bin"
